Close #485: Bump logger-f to 2.4.0
The older version of logger-f with the latest sbt-docusaur is causing `java.lang.NoSuchMethodError: 'loggerf.core.Log loggerf.instances.cats$.logF`